config/routes.rb
Rails.application.routes.draw do
  resource :loan_applications, only: [:index, :show]
  resource :events, only: [:create]

  root controller: :loan_applications, action: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ActiveRecord::Base
  class << self
    def process(event_data)
      event_class = event_data[:event_type].constantize

      event = event_class.new(event_data)
      if event.valid?
        create!(
          payload: event.to_h,
          name: event_class.to_s,
          aggregate_root_uuid: event_data[:aggregate_root_uuid],
          aggregate_root_name: event_data[:aggregate_root_name],
        )
        else redirect_to event_data[:referer]
      end
    end
  end
end

app/models/events/signed_up.rb
class Events::SignedUp
  include ActiveModel::Model

  attr_accessor :email, :password

  def initialize(attributes = {})
    @email = attributes[:email]
    @password = attributes[:password]
  end

  def to_h
    { email: email, password: password }
  end
end

app/models/loan_application.rb
class LoanApplication
  include ActiveModel::Model

  attr_accessor :stage

  def initialize
    @stage = :sign_up
  end

  class << self
    def load(uuid)
      events = Event.where(aggregate_root_uuid: uuid, aggregate_root_name: self.to_s).order(created_at: :asc)
      events.reduce(LoanApplication.new) { |loan_app, event| loan_app.apply(event) }
    end
  end

  def apply(event)
    Rails.logger.error(event.name)
    if event.name == "Events::SignedUp"
      @stage = :business_info
    end
    self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ActionController::Base
  def create


    Event.process(params[:event])
  end
end

app/controllers/loan_applications_controller.rb
class LoanApplicationsController < ApplicationController
  before_action do
    loan_app_uuid = session[:loan_application_uuid] ||= SecureRandom.uuid
    @loan_application_uuid =  loan_app_uuid
  end

  def index

  end

  def show
    loan_application = LoanApplication.load(@loan_application_uuid)

    case loan_application.stage
    when :sign_up
      render :first_step
    when :business_info
      render :business_info_step
    else
      raise :whups
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventSourcing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/loan_applications/business_info_step.html.erb
Business info

app/views/loan_applications/first_step.html.erb
<%= form_for Events::SignedUp.new, as: :event, url: events_path do |f| %>
    <%= f.text_field(:email) %>
    <br>
    <%= f.text_field(:password) %>
    <%= f.hidden_field(:event_type, value: Events::SignedUp.to_s) %>
    <%= f.hidden_field(:aggregate_root_uuid, value: @loan_application_uuid) %>
    <%= f.hidden_field(:aggregate_root_name, value: LoanApplication) %>
    <%= f.hidden_field(:referer, value: 'first_step') %>


    <%= f.submit 'Sign up' %>
<% end %>

app/views/loan_applications/index.html.erb
<%= link_to 'Start new loan application', LoanApplication.new %>